ALTER TABLE pacientes ADD COLUMN IF NOT EXISTS "usuarioId" INTEGER;
ALTER TABLE historia_clinica ADD COLUMN IF NOT EXISTS "usuarioId" INTEGER;
ALTER TABLE ficha_medica ADD COLUMN IF NOT EXISTS "usuarioId" INTEGER;
