ALTER TABLE historia_clinica ADD COLUMN IF NOT EXISTS cancelado BOOLEAN DEFAULT FALSE;
ALTER TABLE historia_clinica ADD COLUMN IF NOT EXISTS descuento DECIMAL(12,2) DEFAULT 0;
ALTER TABLE historia_clinica ADD COLUMN IF NOT EXISTS "precioConDesceunto" DECIMAL(12,2) DEFAULT 0;
